import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="admin",
    password="admin"
)
cur = db.cursor()

cur.execute('DROP DATABASE IF EXISTS CBE_STOCKS')
# database creation
cur.execute("CREATE DATABASE IF NOT EXISTS CBE_STOCKS")
cur.execute("USE CBE_STOCKS")


# table creation


s = ['''CREATE TABLE IF NOT EXISTS OUTVOUCHERS (
	ID INT NOT NULL AUTO_INCREMENT,
	ReceiverID INT NOT NULL,
	DateOfReceival TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Approval INT NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);''',

     '''CREATE TABLE IF NOT EXISTS INVOUCHERS (
	ID INT NOT NULL AUTO_INCREMENT,
	SupplierID INT NOT NULL,
	DateOfReceival TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Approval INT NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
);''',

     '''CREATE TABLE IF NOT EXISTS VOUCHERITEMS (
	vID INT NOT NULL,
	vType INT NOT NULL,
    vItemID INT NOT NULL,
	vItemQty INT NOT NULL,
	PRIMARY KEY (vID, vItemID)
);
''',
     '''CREATE TABLE IF NOT EXISTS ITEMS (
	ID INT NOT NULL AUTO_INCREMENT,
	CategoryID INT NOT NULL,
	Name varchar(255) NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY (ID)
);
''',
     '''CREATE TABLE IF NOT EXISTS CATEGORIES (
	ID INT NOT NULL AUTO_INCREMENT,
	Name varchar(255) NOT NULL,
	PRIMARY KEY (ID)
);
''',
     '''CREATE TABLE IF NOT EXISTS USERS (
	ID INT NOT NULL AUTO_INCREMENT,
	Name varchar(255) NOT NULL,
	Email varchar(50) NOT NULL,
	password varchar(100) NOT NULL,
	AuthType INT NOT NULL,
	PRIMARY KEY (ID)
);
''',

     #  '''ALTER TABLE VOUCHERITEMS ADD FOREIGN KEY (vID) REFERENCES OUTVOUCHERS(ID);''',

     #  '''ALTER TABLE VOUCHERITEMS ADD FOREIGN KEY (vID) REFERENCES INVOUCHERS(ID);''',

     '''ALTER TABLE VOUCHERITEMS ADD FOREIGN KEY (vItemID) REFERENCES ITEMS(ID);''',

     '''ALTER TABLE ITEMS ADD FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(ID);'''

     #  '''ALTER TABLE OUTVOUCHERS AUTO_INCREMENT=100001;'''

     #  '''ALTER TABLE INVOUCHERS AUTO_INCREMENT=200001;'''
     ]


for i in s:
    cur.execute(i)
